name: Test

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
  - cron: "0 7 * * *"

jobs:

  test-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install YAKS
        uses: ./

      - name: Test
        shell: bash
        run: |
          yaks version

  test-default:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install YAKS
        uses: ./
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Test
        shell: bash
        run: |
          yaks version

  test-with-custom-version:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        version:
        - v0.4.0
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install YAKS
        with:
          version: ${{ matrix.version }}
        uses: ./

      - name: Test
        shell: bash
        run: |
          yaks version
